---
# Variables for this exercise
ansible_python_interpreter: /usr/bin/python3

## certbot: enable cockpit changes
enable_cockpit: yes

redhat:
  - git
  - net-snmp

fedora:
  - git
  - net-snmp
  - python-unversioned-command

certbot:
  acme_email: security@erickson.is
  domains: "{{ ansible_fqdn }}"

snmp:
  readonly:
    ro_comm_string:
      access:
        - 192.168.1.250
    ro_comm_string2:
      access:
        - 192.168.1.250
  contact: node-alerts@ashbyte.com
  location: '[45.484,-122.794]'

chrony_commands:
  allow:
    - 10.0.0.0/8
    - 172.16.0.0/12
  hwtimestamp: '*'
  keyfile: /etc/chrony.keys
  log: 'measurements statistics tracking'
  driftfile: /var/lib/chrony/drift
  logdir: /var/log/chrony
  makestep: '1.0 3'
  minsources: 2
  rtcsync: True

dnf_automatic: true

## "yes" or "no"
dnf_apply_updates: yes

dnf_email_from: "node_alert@{{ ansible_fqdn }}"
dnf_email_to: node-alerts@ashbyte.com
dnf_email_host: smtp-foward.ashbyte.com
